/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

import javax.swing.JOptionPane;

/**
 *
 * @author JM Gutierrez
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    public void Mostrar(double area,double perimetro){
        txtA.setText(null);
        txtA.append("El area es: "+area+" m\nEl perimetro es: "+perimetro+" m");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        txtLad1 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLad2 = new javax.swing.JTextField();
        txtLad3 = new javax.swing.JTextField();
        txtLad4 = new javax.swing.JTextField();
        cboCuadrilatero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lado 1:");

        jLabel2.setText("Lado 4:");

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnCalcular.setText("CALCULAR AREA Y PERIMETRO");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel3.setText("Lado 2:");

        jLabel4.setText("Lado 3:");

        cboCuadrilatero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rectangulo", "Paralelogramo", "Rombo", "Trapecio" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(cboCuadrilatero, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLad1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLad2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLad3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLad4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLad1, txtLad2, txtLad3, txtLad4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboCuadrilatero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String tex1=txtLad1.getText();
        String tex2=txtLad2.getText();
        String tex3=txtLad3.getText();
        String tex4=txtLad4.getText();
        if(tex1.compareTo("")!=0&&tex2.compareTo("")!=0&&tex3.compareTo("")!=0&&tex4.compareTo("")!=0){
            int Cuadri=cboCuadrilatero.getSelectedIndex();
            double lad1=Integer.parseInt(tex1);
            double lad2=Integer.parseInt(tex2);
            double lad3=Integer.parseInt(tex3);
            double lad4=Integer.parseInt(tex4);
            double area=0,perimetro=0;
            switch(Cuadri){
                case 0: Cuadrilateros Rectangulo=new Cuadrilateros(lad1,lad2,lad3,lad4);
                        if(Rectangulo.esRectangulo()){
                            area=Rectangulo.AreaRec();
                            perimetro=Rectangulo.Perimetro();break;
                        }else{
                            JOptionPane.showMessageDialog(null,"No es rectangulo","ALERTA",JOptionPane.WARNING_MESSAGE);break;
                        }
                case 1: Cuadrilateros Paralelogramo=new Cuadrilateros(lad1,lad2,lad3,lad4);
                        if(Paralelogramo.esParalelogramo()){
                            double alturaP=Double.parseDouble(JOptionPane.showInputDialog(null,"ALTURA DEL PARALELOGRAMO: "));
                            area=Paralelogramo.AreaPar(alturaP);
                            perimetro=Paralelogramo.Perimetro();break;
                        }else{
                            JOptionPane.showMessageDialog(null,"No es Paralelogramo","ALERTA",JOptionPane.WARNING_MESSAGE);break;
                        }
                        
                case 2: Cuadrilateros Rombo=new Cuadrilateros(lad1,lad2,lad3,lad4);
                        if(Rombo.esRombo()){
                            double Dmayor=Double.parseDouble(JOptionPane.showInputDialog(null,"DIAGONAL MAYOR "));
                            double Dmenor=Double.parseDouble(JOptionPane.showInputDialog(null,"DIAGONAL MENOR "));
                            area=Rombo.AreaRom(Dmayor, Dmenor);
                            perimetro=Rombo.Perimetro();break;
                        }else{
                            JOptionPane.showMessageDialog(null,"No es Rombo","ALERTA",JOptionPane.WARNING_MESSAGE);break;
                        }
                        
                default:Cuadrilateros Trapecio=new Cuadrilateros(lad1,lad2,lad3,lad4);
                        if(Trapecio.esTrapecio()){
                            double alturaT=Double.parseDouble(JOptionPane.showInputDialog(null,"ALTURA DEL TRAPECIO: "));
                            area=Trapecio.AreaTra(alturaT);
                            perimetro=Trapecio.Perimetro();   
                        }else{
                            JOptionPane.showMessageDialog(null,"No es Trapecio","ALERTA",JOptionPane.WARNING_MESSAGE);break;
                        }
            }
            Mostrar(area,perimetro);
        }else{
            JOptionPane.showMessageDialog(null,"Una casilla esta vacia","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox<String> cboCuadrilatero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtLad1;
    private javax.swing.JTextField txtLad2;
    private javax.swing.JTextField txtLad3;
    private javax.swing.JTextField txtLad4;
    // End of variables declaration//GEN-END:variables
}
