/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pregunta_1;
import javax.swing.JOptionPane;
/**
 *
 * @author alumnoUSMP
 */
public class Ejercicio extends javax.swing.JFrame {
int A[]=new int[Integer.parseInt(JOptionPane.showInputDialog("Ingrese cantidad de estudiantes:"))], indiceA=0, cPar=0, cImP=0, B[]=new int[A.length], indiceB=0;

    /**
     * Creates new form Ejercicio
     */
    public Ejercicio() {
        initComponents();
    }
    public void registrar(int e){
        A[indiceA]=e;
        indiceA++;
    }
    public void validar(int e){
        if(e%2==0){
            cPar++;
        }else{
            cImP++;
        }
    }
    public void buscar(int e){
        int iPos=0;
        String texto="";
        boolean y=false;
        for(int c=0;c<indiceA;c++){
            if(A[c]==e){
                texto+=c+"; ";
                iPos++;
                y=true;
            }
        }
        if(y){
            JOptionPane.showMessageDialog(null,"Esta en la posicion "+texto+" y la cantidad de veces que se repite es "+iPos);
        }else{
            JOptionPane.showMessageDialog(null,"NUMERO NO ENCONTRADO","ERROR",JOptionPane.WARNING_MESSAGE);
        }
    }
    public void eliminar(int e){
        boolean x=false;
        for(int c=0;c<indiceA;c++){
            if(A[c]==e){
               for(int pos=c;pos<indiceA-1;pos++){
                   A[pos]=A[pos+1];
               }
               indiceA--;
               c=-1;
               x=true;
            }
        }
        if(x){
            int aux[]=new int[A.length];
            for(int i=0;i<indiceA;i++){
                aux[i]=A[i];
            }
            A=aux;
        }else{
             JOptionPane.showMessageDialog(null,"NUMERO NO ENCONTRADO","ERROR",JOptionPane.WARNING_MESSAGE);
        }
       
    }
    public void ordenar(){
        int x;
        for(int c=0;c<indiceA;c++){
            if(A[c]%2!=0){
                B[indiceB]=A[c];
                indiceB++;
            }  
        }
        x=indiceB;
        for(int c=0;c<indiceB;c++){
            for(int i=c+1;i<indiceB;i++){
                if(B[c]>=B[i]){
                    int aux=B[c];
                    B[c]=B[i];
                    B[i]=aux;
                }
            }
        }
        for(int c=indiceB;c<indiceA;c++){
            if(A[c]%2==0){
                B[indiceB]=A[c];
                indiceB++;
            }  
        }
        for(int c=x;c<indiceB;c++){
            for(int i=c+1;i<indiceB;i++){
                if(B[c]>=B[i]){
                    int aux=B[c];
                    B[c]=B[i];
                    B[i]=aux;
                }
            }
        }
        
    }
    public void mostrar(){
        String t=JOptionPane.showInputDialog("1.Vector A\n2.Vector B\n3. Ambos");
        int n=Integer.parseInt(t);
        txtA.setText(null);
        switch(n){
            default:
                
                JOptionPane.showMessageDialog(null,"ERROR","ERROR",JOptionPane.ERROR_MESSAGE);
                break;
            case 1: 
                for(int c=0;c<indiceA;c++){
                    if(c<indiceA-1){
                        txtA.append(A[c]+"; ");
                    }else{
                        txtA.append(String.valueOf(A[c]));
                    }
                }
                break;
            case 2:
                for(int c=0;c<indiceB;c++){
                    if(c<indiceB-1){
                        txtA.append(B[c]+"; ");
                    }else{
                        txtA.append(String.valueOf(B[c]));
                    }
                }
                break;
            case 3:
                txtA.append("VECTOR A: \n");
                for(int c=0;c<indiceA;c++){
                    if(c<indiceA-1){
                        txtA.append(A[c]+"; ");
                    }else{
                        txtA.append(String.valueOf(A[c]));
                    }
                }
                txtA.append("\n");
                txtA.append("VECTOR B \n");
                for(int c=0;c<indiceB;c++){
                    if(c<indiceB-1){
                        txtA.append(B[c]+"; ");
                    }else{
                        txtA.append(String.valueOf(B[c]));
                    }
                }           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        btnParesEimpares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistrar.setText("REGISTRAR EDAD");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnParesEimpares.setText("CANTIDAD DE EDADES PARES E IMPARES");
        btnParesEimpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParesEimparesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnParesEimpares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnEliminar)
                                .addComponent(btnBuscar)
                                .addComponent(btnOrdenar)
                                .addComponent(btnMostrar))
                            .addComponent(btnRegistrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar, btnEliminar, btnMostrar, btnOrdenar, btnRegistrar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOrdenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrar))
                    .addComponent(jScrollPane1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnParesEimpares)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String t=JOptionPane.showInputDialog("INGRESE EDAD:");
        int e=Integer.parseInt(t);
        eliminar(e);
        JOptionPane.showMessageDialog(null, "ELEMENTOS ELIMINADOS","EXITO",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(indiceA<A.length){
            String e=JOptionPane.showInputDialog("Digite edad:");
        int edad=Integer.parseInt(e);
        
        if(edad>=15){
            registrar(edad);
            validar(edad);
            JOptionPane.showMessageDialog(null, "EDAD REGISTRADA","EXITO",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(null,"EDAD NO ACEPTADA","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(this,"Vector Lleno","ERROR",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        ordenar();
        JOptionPane.showMessageDialog(null, "ELEMENTOS ORDENADOS","EXITO",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_btnMostrarActionPerformed

    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String t=JOptionPane.showInputDialog("Ingresar edad:");
       int e=Integer.parseInt(t);
       buscar(e);
       
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnParesEimparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParesEimparesActionPerformed
        JOptionPane.showMessageDialog(null,"La cantidad de pares es "+cPar+" e impares es "+cImP);
        
    }//GEN-LAST:event_btnParesEimparesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnParesEimpares;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    // End of variables declaration//GEN-END:variables
}
