/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio_1;

import javax.swing.JOptionPane;

/**
 *
 * @author jmgut
 */
public class Formulario extends javax.swing.JFrame {
    int vCodigo[]=new int[999999];
    char Tipo[]=new char[999999];
    char vResultado[]=new char[999999];
    int indice=0;
    int pos;
    boolean xV=false,yV=false;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    public boolean codigoRepetido(int cod){
        boolean x=false;
        for(int c=indice-1;c>=0;c--){
            if(cod==vCodigo[c])
                x=true;
        }
        return x;
    }
    public void Mostrar(){
        txtA.setText(null);
        for(int c=0;c<indice;c++){
            txtA.append("POS: ["+c+"]\n");
            if(Tipo[c]=='T'){
                txtA.append("Tipo : Camión" +"\n");
            }else{
                txtA.append("Tipo : Auto" +"\n");
            }
            txtA.append("CODIGO: "+vCodigo[c]+"\n");
            txtA.append("Resultado: "+vResultado[c]+"\n-\n");
        }
    }
    public void MostrarResultados(){
        txtA.setText(null);
        for(int c=0;c<pos;c++){
            txtA.append("POS: ["+c+"]\n");
            if(Tipo[c]=='T'){
                txtA.append("Tipo : Camión" +"\n");
            }else{
                txtA.append("Tipo : Auto" +"\n");
            }
            txtA.append("CODIGO: "+vCodigo[c]+"\n");
            txtA.append("Resultado: "+vResultado[c]+"\n-\n");
        }
    }
    public void MostrarNoResultado(){
        txtA.setText(null);
        for(int c=pos;c<indice;c++){
            txtA.append("POS: ["+c+"]\n");
            if(Tipo[c]=='T'){
                txtA.append("Tipo : Camión" +"\n");
            }else{
                txtA.append("Tipo : Auto" +"\n");
            }
            txtA.append("CODIGO: "+vCodigo[c]+"\n");
            txtA.append("Resultado: "+vResultado[c]+"\n-\n");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        txtTipoCarro = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnTesteo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnReproceso = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("TIPO DE VEHICULO");

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnTesteo.setText("TESTEO");
        btnTesteo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTesteoActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnReproceso.setText("REPROCESO");
        btnReproceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReprocesoActionPerformed(evt);
            }
        });

        btnListar.setText("LISTAR");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReproceso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTesteo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTesteo)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReproceso)
                    .addComponent(btnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        boolean y=false;
        int pos,qE=0;
        for(int i=0;i<indice;i++){
            if(vResultado[i]=='D'){
                y=true;
                qE++;
                for(int j=i;j<indice-1;j++){
                    vResultado[j]=vResultado[j+1];
                }
                indice--;
                i=-1; 
            }
        }
        if(y==true){
            char aux[]=new char[vResultado.length];
                for(int c=0;c<indice;c++){
                        aux[c]=vResultado[c];
                }
            vResultado=aux;
            JOptionPane.showMessageDialog(this, "Los vehiculos fueron eliminados");
        }else{
           JOptionPane.showMessageDialog(this, "NO HAY VEHICULOS QUE ELIMINAR");
        }
        Mostrar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnReprocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReprocesoActionPerformed
        if(xV){
            for(int c=0;c<pos;c++){
                if(vResultado[c]=='R'){
                    if(Tipo[c]=='T'){
                        vResultado[c]=new TestCamion().realizarTest();
                    }else{
                        vResultado[c]=new TestAuto().realizarTest();
                    }
                }
            }
            Mostrar();
        }else{
            JOptionPane.showMessageDialog(null,"NO HAY VEHICULOS QUE REPROCESAR","ERROR",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnReprocesoActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        if(xV){  
        int op=Integer.parseInt(JOptionPane.showInputDialog(null,"1. Listar todos los Autos\n2. Listar los autos con resultado\n3. Listar autos que no tienen resultado\nInsertar alternativa:"));
            switch(op){
                case 1:Mostrar();break;
                case 2:MostrarResultados();break;
                case 3:MostrarNoResultado();break;
                default: JOptionPane.showMessageDialog(null,"EN CARACTER NO CORRESPONDE CON NINGUNA ALTERNATIVA","ERROR",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"NO HAY VEHICULOS QUE LISTAR","ERROR",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnTesteoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTesteoActionPerformed
        if(xV){
                for(int c=pos;c<indice;c++){
                    if(Tipo[c]=='T'){
                        vResultado[c]=new TestCamion().realizarTest();
                    }else{
                        vResultado[c]=new TestAuto().realizarTest();
                    }
                    pos=indice;
                }
                Mostrar();
        }else{
            JOptionPane.showMessageDialog(null,"NO HAY VEHICULOS QUE TESTEAR","ERROR",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTesteoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String t=(txtTipoCarro.getText()).trim();
        if(t.compareTo("")!=0&&t.length()==1){
            switch(t.charAt(0)){
                case 'A':xV=true;
                case 'T':int n;
                        do{
                            n=Utilitario.generarAleatorio(1000,5000);
                        }while(codigoRepetido(n)==true);
                        vCodigo[indice]=n;
                        Tipo[indice]=t.charAt(0);
                        indice++;
                        Mostrar();
                        break;
                default:JOptionPane.showMessageDialog(null,"EL CARACTER NO CONCUERDA CON LOS TIPOS DE VEHICULO","ERROR",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"EL TEXTO NO CORRESPONDE","ERROR",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnReproceso;
    private javax.swing.JButton btnTesteo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtTipoCarro;
    // End of variables declaration//GEN-END:variables
}
