/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio_3;

import javax.swing.JOptionPane;

/**
 *
 * @author jmgut
 */
public class Interfaz extends javax.swing.JFrame {
Empleado vecEmps[]=new Empleado[9999];
Estudiante vecEst[]=new Estudiante [9999];
Becario vecBec[]=new Becario [99999];
int indEmps=0;
int indEst=0;
int indBec=0;
boolean xEmps=false,xEst=false,xBec=false;
double sEmps;
double sEst;
double sBec;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    public void MostrarEmps(){
        txtA.setText("EMPLEADOS\n");
        for(int c=0;c<indEmps;c++){
            txtA.append("POSICION: "+"[ "+c+" ]"+"\n");
            txtA.append("NOMBRE: "+vecEmps[c].LeerNombre()+"\n");
            txtA.append("EDAD: "+vecEmps[c].LeerEdad()+"\n");
            txtA.append("SUELDO: "+vecEmps[c].LeerSalario()+"\n");
            txtA.append("TIPOS DE EMPLEADO: "+vecEmps[c].LeerTipo()+"\n");
            
        }
    }
    public void MostrarEst(){
        txtA.setText("ESTUDIANTES\n");
        for(int c=0;c<indEst;c++){
            txtA.append("POSICION: "+"[ "+c+" ]"+"\n");
            txtA.append("NOMBRE: "+vecEst[c].LeerNombre()+"\n");
            txtA.append("EDAD: "+vecEst[c].LeerEdad()+"\n");
            txtA.append("SUELDO: "+vecEst[c].LeerSalario()+"\n");
        }
    }
    public void MostrarBecarios(){
        txtA.setText("BECARIOS\n");
        for(int c=0;c<indBec;c++){
            txtA.append("POSICION: "+"[ "+c+" ]"+"\n");
            txtA.append("NOMBRE: "+vecBec[c].LeerNombre()+"\n");
            txtA.append("EDAD: "+vecBec[c].LeerEdad()+"\n");
            txtA.append("SUELDO: "+vecBec[c].LeerSalario()+"\n");
        }
    }
    public boolean CambiarNombreEmp(int pos,String n){
        boolean xN=false;
        for(int i=0;i<indEmps;i++){
            if(i==pos){
                vecEmps[i].CambiarNombre(n);
                xN=true;
            }
        }
        return xN;
    }
    public boolean CambiarNombreEst(int pos,String n){
        boolean xN=false;
        for(int i=0;i<indEst;i++){
            if(i==pos){
                vecEst[i].CambiarNombre(n);
                xN=true;
            }
        }
        return xN;
    }
    public boolean CambiarNombreBec(int pos,String n){
        boolean xN=false;
        for(int i=0;i<indBec;i++){
            if(i==pos){
                vecBec[i].CambiarNombre(n);
                xN=true;
            }
        }
        return xN;
    }
    public boolean CambiarEdadEmp(int pos,int e){
        boolean xN=false;
        for(int i=0;i<indEmps;i++){
            if(i==pos){
                vecEmps[i].CambiarEdad(e);
                xN=true;
            }
        }
        return xN;
    }
    public boolean CambiarEdadEst(int pos,int e){
        boolean xN=false;
        for(int i=0;i<indEst;i++){
            if(i==pos){
                vecEst[i].CambiarEdad(e);
                xN=true;
            }
        }
        return xN;
    }
    public boolean CambiarEdadBec(int pos,int e){
        boolean xN=false;
        for(int i=0;i<indBec;i++){
            if(i==pos){
                vecBec[i].CambiarEdad(e);
                xN=true;
            }
        }
        return xN;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cboPersona = new javax.swing.JComboBox<>();
        txtNom = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btncSueldo = new javax.swing.JButton();
        btncNom = new javax.swing.JButton();
        cboGener = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCambiarEdad = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        jLabel2.setText("Edad:");

        cboPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Estudiante", "Becario" }));

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btncSueldo.setText("CAMBIAR SUELDO");
        btncSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncSueldoActionPerformed(evt);
            }
        });

        btncNom.setText("CAMBIAR NOMBRE");
        btncNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncNomActionPerformed(evt);
            }
        });

        cboGener.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        jLabel4.setText("T. de trabajador:");

        jLabel5.setText("Genero:");

        btnCambiarEdad.setText("CAMBIAR EDAD");
        btnCambiarEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEdadActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncSueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboPersona, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(cboGener, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNom)))
                    .addComponent(btnCambiarEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboGener, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncSueldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarEdad)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btncNom, btncSueldo});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        String tip=JOptionPane.showInputDialog(null,"Escribir Alternativa:\n1. EMPLEADO\n2. ESTUDIANTE\n3. BECARIO:",JOptionPane.QUESTION_MESSAGE).toUpperCase();
        switch(tip){
            case "EMPLEADO":MostrarEmps();break;
            case "ESTUDIANTE":MostrarEst();break;
            case "BECARIO":MostrarBecarios();break;
            default:JOptionPane.showMessageDialog(null,"LA RESPUESTA NO CONCUERDA CON NINGUNA OPCION","ENTRADA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btncSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncSueldoActionPerformed
        String per=JOptionPane.showInputDialog(null,"1. EMPLEADO\n2. ESTUDIANTE\n3. BECARIO:",JOptionPane.QUESTION_MESSAGE).toUpperCase();
        double sueldoN=Double.parseDouble(JOptionPane.showInputDialog(null,"INSERTAR NUEVO SUELDO:",JOptionPane.QUESTION_MESSAGE));
        switch(per){
            case "EMPLEADO": 
                    if(sEmps!=0){
                        Empleado.CambiarSalario(sueldoN);
                        sEmps=sueldoN;
                        MostrarEmps();
                    }else{
                        JOptionPane.showMessageDialog(null,"NO SE LE ASIGNO UN SUELDO A LOS EMPLEADOS","ERROR",JOptionPane.WARNING_MESSAGE);
                    }
                    break;
            case "ESTUDIANTE": 
                    if(sEst!=0){
                        Estudiante.CambiarSalario(sueldoN);
                        sEst=sueldoN;
                        MostrarEst();
                    }else{
                        JOptionPane.showMessageDialog(null,"NO SE LE ASIGNO UN SUELDO A LOS ESTUDIANTES","ERROR",JOptionPane.WARNING_MESSAGE);
                    }
                    break;
            case "BECARIO": 
                    if(sBec!=0){
                        Becario.CambiarSalario(sueldoN);
                        sBec=sueldoN;
                        MostrarBecarios();
                    }else{
                        JOptionPane.showMessageDialog(null,"NO SE LE ASIGNO UN SUELDO A LOS BECARIOS","ERROR",JOptionPane.WARNING_MESSAGE);
                    }
                    break;
            default:JOptionPane.showMessageDialog(null,"LA RESPUESTA NO CONCUERDA CON NINGUNA OPCION","ENTRADA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btncSueldoActionPerformed

    private void btncNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncNomActionPerformed
        String per=JOptionPane.showInputDialog(null,"1. EMPLEADO\n2. ESTUDIANTE\n3. BECARIO:",JOptionPane.QUESTION_MESSAGE).toUpperCase();
        int pos=Integer.parseInt(JOptionPane.showInputDialog(null,"Posicion del usuario:",JOptionPane.QUESTION_MESSAGE));
        String nombreN=JOptionPane.showInputDialog(null,"Insertar nuevo nombre:",JOptionPane.QUESTION_MESSAGE).toUpperCase();
        switch(per){
            case "EMPLEADO":
                            if(CambiarNombreEmp(pos,nombreN)){
                                JOptionPane.showMessageDialog(null,"NOMBRE CAMBIADO EXITOSAMENTE","LISTO",JOptionPane.INFORMATION_MESSAGE);
                                MostrarEmps();
                            }else{
                                JOptionPane.showMessageDialog(null,"POSICION NO ENCONTRADA","ERROR",JOptionPane.WARNING_MESSAGE);
                            }break;
            case "ESTUDIANTE": 
                            if(CambiarNombreEst(pos,nombreN)){
                                JOptionPane.showMessageDialog(null,"NOMBRE CAMBIADO EXITOSAMENTE","LISTO",JOptionPane.INFORMATION_MESSAGE);
                                MostrarEst();
                            }else{
                                JOptionPane.showMessageDialog(null,"POSICION NO ENCONTRADA","ERROR",JOptionPane.WARNING_MESSAGE);
                            }
                            break;
            case "BECARIO": 
                            if(CambiarNombreBec(pos,nombreN)){
                                JOptionPane.showMessageDialog(null,"NOMBRE CAMBIADO EXITOSAMENTE","LISTO",JOptionPane.INFORMATION_MESSAGE);
                                MostrarBecarios();
                            }else{
                                JOptionPane.showMessageDialog(null,"POSICION NO ENCONTRADA","ERROR",JOptionPane.WARNING_MESSAGE);
                            }
                            break;
            default:JOptionPane.showMessageDialog(null,"LA RESPUESTA NO CONCUERDA CON NINGUNA OPCION","ENTRADA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btncNomActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String tex1=txtNom.getText();
        String tex2=txtEdad.getText();
        int persona=cboPersona.getSelectedIndex();
        if(tex1.compareTo("")!=0&&tex1.compareTo("")!=0&&tex1.compareTo("")!=0){
            int gen=cboGener.getSelectedIndex();
            String genero;
            switch(gen){
                case 0: genero="HOMBRE";break;
                default: genero="MUJER";
            }
            String nombre=tex1.toUpperCase();
            int edad=Integer.parseInt(tex2);
            if(edad>18&&edad<60){
                switch(persona){ 
                case 0: if(xEmps==false){
                            sEmps=Double.parseDouble(JOptionPane.showInputDialog(null,"COLOCAR SUELDO DE LOS EMPLEADOS","ENTRADA",JOptionPane.QUESTION_MESSAGE));
                            xEmps=true;
                        }
                        String tEmp=JOptionPane.showInputDialog(null,"1.Ejecutivo\n2.Comercial\nESCRIBIR tipo de empleado:",JOptionPane.QUESTION_MESSAGE).toUpperCase();
                        switch(tEmp){
                            case "EJECUTIVO":Ejecutivo C1=new Ejecutivo(nombre, edad,genero, sEmps,tEmp);
                                            vecEmps[indEmps]=C1;
                                            indEmps++;
                                            break;
                            case "COMERCIAL":Comercial C2=new Comercial(nombre, edad,genero, sEmps,tEmp);
                                            vecEmps[indEmps]=C2;
                                            indEmps++;
                                            break;
                            default: JOptionPane.showMessageDialog(null,"Esta no pertecenece a las alternativas ","ALERTA",JOptionPane.WARNING_MESSAGE);
                        }
                        break;
                case 1:if(xEst==false){
                            sEst=Double.parseDouble(JOptionPane.showInputDialog(null,"COLOCAR SUELDO DE LOS ESTUDIANTES","ENTRADA",JOptionPane.QUESTION_MESSAGE));
                            xEst=true;
                        }
                        Estudiante B2=new Estudiante(nombre, edad,genero, sEst);
                        vecEst[indEst]=B2;
                        indEst++;
                        break;
                default:if(xBec==false){
                            sBec=Double.parseDouble(JOptionPane.showInputDialog(null,"COLOCAR SUELDO DE LOS BECARIOS","ENTRADA",JOptionPane.QUESTION_MESSAGE));
                            xBec=true;
                        }
                        Becario B3=new Becario(nombre, edad,genero, sBec);
                        vecBec[indBec]=B3;
                        indBec++;
                }
            }else{
                JOptionPane.showMessageDialog(null,"DEBE TENER MAS DE 18 AÑOS Y MENOR DE 60","ALERTA",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"HAY CASILLAS VACIAS","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCambiarEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEdadActionPerformed
        String per=JOptionPane.showInputDialog(null,"1. EMPLEADO\n2. ESTUDIANTE\n3. BECARIO:",JOptionPane.QUESTION_MESSAGE).toUpperCase();
        int pos=Integer.parseInt(JOptionPane.showInputDialog(null,"Posicion del usuario:",JOptionPane.QUESTION_MESSAGE));
        int edadN=Integer.parseInt(JOptionPane.showInputDialog(null,"Insertar nuevo edad:",JOptionPane.QUESTION_MESSAGE));
        switch(per){
            case "EMPLEADO":
                            if(CambiarEdadEmp(pos,edadN)){
                                JOptionPane.showMessageDialog(null,"EDAD CAMBIADA EXITOSAMENTE","LISTO",JOptionPane.INFORMATION_MESSAGE);
                                MostrarEmps();
                            }else{
                                JOptionPane.showMessageDialog(null,"POSICION NO ENCONTRADA","ERROR",JOptionPane.WARNING_MESSAGE);
                            }break;
            case "ESTUDIANTE": 
                            if(CambiarEdadEst(pos,edadN)){
                                JOptionPane.showMessageDialog(null,"EDAD CAMBIADA EXITOSAMENTE","LISTO",JOptionPane.INFORMATION_MESSAGE);
                                MostrarEst();
                            }else{
                                JOptionPane.showMessageDialog(null,"POSICION NO ENCONTRADA","ERROR",JOptionPane.WARNING_MESSAGE);
                            }
                            break;
            case "BECARIO": 
                            if(CambiarEdadBec(pos,edadN)){
                                JOptionPane.showMessageDialog(null,"EDAD CAMBIADA EXITOSAMENTE","LISTO",JOptionPane.INFORMATION_MESSAGE);
                                MostrarBecarios();
                            }else{
                                JOptionPane.showMessageDialog(null,"POSICION NO ENCONTRADA","ERROR",JOptionPane.WARNING_MESSAGE);
                            }
                            break;
            default:JOptionPane.showMessageDialog(null,"LA RESPUESTA NO CONCUERDA CON NINGUNA OPCION","ENTRADA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCambiarEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCambiarEdad;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btncNom;
    private javax.swing.JButton btncSueldo;
    private javax.swing.JComboBox<String> cboGener;
    private javax.swing.JComboBox<String> cboPersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
