/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Prueba_de_Embarazo;

/**
 *
 * @author jmgut
 */
public class Formulario extends javax.swing.JFrame {
Paciente []pac=new Paciente[5];
int indice=0;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    public boolean codigoRepetido(int cod){
        for(int c=0;c<indice;c++){
            if(pac[c].getCod()==cod){
                return true;
            }
        }
        return false;
    }
    public int Buscar(int cod){
        for(int i=0;i<indice;i++){
            if(pac[i].getCod()==cod){
                return i;
            }
        }
        return -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        txtNombre = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnPrueba = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE");

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnRegistrar.setText("REGISTRAR PACIENTE");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnListar.setText("LISTAR PACIENTES");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnPrueba.setText("PRUEBA");
        btnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR PACIENTE");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscar)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar)
                    .addComponent(btnPrueba))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar, btnListar, btnPrueba, btnRegistrar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrueba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(indice<pac.length){
            String t=txtNombre.getText().trim().toUpperCase();
            if(t.equals("")==false){
                String n=t;
                int c;
                do{
                    c=Utilitario.generarAleatorio(3500, 4499);
                }while(codigoRepetido(c)==true);
                int edad=Utilitario.generarAleatorio(1, 45);
                String sexo=Utilitario.generarAleatorio();
                if(edad>=15){
                    if(sexo.equals("FEMENINO")){
                        pac[indice]=new Paciente(c, n, edad, sexo);
                        indice++;
                    }else{
                        Utilitario.Mensaje("EL SEXO ES MASCULINO, NO SE REGISTRO");
                    }
                }else{
                    Utilitario.Mensaje("MENOR DE EDAD, VISITE A SU MEDICO");
                }
            }else{
                Utilitario.MensajeError("INSERTAR NOMBRE");
            }
        }else{
            Utilitario.MensajeError("NO SE PUEDE REGISTRAR MAS PACIENTES");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        if(indice>0){
            txtA.setText(null);
            for(int c=0;c<indice;c++){
                txtA.append("\nPACIENTE NRO: "+(c+1)+"\n");
                txtA.append("   CODIGO: "+pac[c].getCod()+"\n");
                txtA.append("   NOMBRE: "+pac[c].getNombre()+"\n");
                txtA.append("   EDAD: "+pac[c].getEdad()+"\n");
                txtA.append("   SEXO: "+pac[c].getSexo()+"\n");
            }
        }else{
            Utilitario.MensajeError("NO HAY PACIENTE PARA LISTAR");
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActionPerformed
        int c=Integer.parseInt(Utilitario.ingreso("INGRESAR CODIGO DE PACIENTE"));
        int pos=Buscar(c);
        if(pos>=0){
            if(pac[pos].getIndice_p()<pac[pos].getPrueba().length){
                int d=Integer.parseInt(Utilitario.ingreso("INGRESAR TIPO DE PRUEBA\n1.PRUEBA DE SANGRE\n2.PRUEBA DE ORINA"));
                switch(d){
                    case 1: pac[pos].setPrueba(new P_Sangre().realizarPrueba()); 
                    Utilitario.Mensaje("SE REALIZO LA PRUEBA DE SANGRE");
                    break;
                    case 2: pac[pos].setPrueba(new P_Orina().realizarPrueba());
                    Utilitario.Mensaje("SE REALIZO LA PRUEBA DE ORINA");
                    break;
                    default:Utilitario.MensajeError("LA RESPUESTA NO CORRESPONDE CON LAS ALTERNATIVAS");
                }
            }else{
                Utilitario.MensajeError("NO SE PUEDE REALIZAR MAS PRUEBAS");
            }
        }else{
            Utilitario.MensajeError("NO SE ENCONTRO AL PACIENTE");
        }
    }//GEN-LAST:event_btnPruebaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int cod=Integer.parseInt(Utilitario.ingreso("INGRESAR CODIGO DE PACIENTE"));
        int pos=Buscar(cod);
        if(pos>=0){
            txtA.setText("BUSQUEDA DEL PACIENTE\n");
            txtA.append("--------------------------------\n");
            txtA.append("CODIGO: "+pac[pos].getCod()+"\n");
            txtA.append("NOMBRE: "+pac[pos].getNombre()+"\n");
            txtA.append("EDAD: "+pac[pos].getEdad()+"\n");
            txtA.append("SEXO: "+pac[pos].getSexo()+"\n");
            txtA.append("PRUEBAS \n");
            for(int c=0;c<pac[pos].getIndice_p();c++){
                txtA.append(" -- "+pac[pos].getPrueba()[c]+"\n");
            }
        }else{
            Utilitario.Mensaje("NO SE ENCONTRO AL PACIENTE");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPrueba;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
