
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USMP
 */
public class ej1 extends javax.swing.JFrame {
int UNO[];
int indice1;
int DOS[];
int indice2;
int TRES[];
int indice3;
    /** Creates new form ej1 */
    public ej1() {
        initComponents();
    }
    public void generarVector(){
        for(int c=0;c<UNO.length;c++){
            UNO[c]=(int)(Math.random()*(90-30+1)+30);
            indice1++;
        }
    }
    public void mostrarVector(){
        txtA1.setText(null);
        for(int c = 0;c < indice1 ; c++){
            txtA1.append("[" + c + "]-->" + UNO[c] + "\n");
        }
    }
    public void mostrarPos(int nbus){
        txtA2.setText(null);
        for(int c = 0; c < indice2 ; c++){
            txtA2.append(nbus + "-->[" + DOS[c] + "]" + "\n");
        }
    }
    public boolean buscarVector(int nbus){
        boolean centinela=false;
        for(int c=0;c<indice1;c++){
            if(nbus==UNO[c]){
                DOS[indice2]=c;
                indice2++;
                centinela=true;
            }
        }
        return centinela;
    }
    public void modificarValor(int vmod){
        for(int c=0;c<indice2;c++){
            for(int i=0;i<indice1;i++){
                if(DOS[c]==i){
                    UNO[i]=vmod;
                }
            }
        }
    }
    public void moverC(){
        for(int c=0;c<indice1;c++){
            TRES[c]=UNO[c];
            indice3++;
        }
    }
    public void ordenarC(){
        int contadorPARES=0;
        for(int c=0;c<indice3;c++){
            if(TRES[c]%2 == 0){
                int auxiliar = TRES[contadorPARES];
                TRES[contadorPARES] = TRES[c];
                contadorPARES++;
            }  
        }
        for(int c=0;c<contadorPARES;c++){
            for(int i=c;i<contadorPARES;i++){
                if(TRES[c] <= TRES[i]){
                    int auxiliar = TRES[c];
                    TRES[c] = TRES[i];
                    TRES[i] = auxiliar;
                }
            }
        }
        
        for(int c = contadorPARES; c < indice3;c++){
            for(int i = c;i < indice3;i++){
                if(TRES[c] <= TRES[i]){
                    int numero = TRES[c];
                    TRES[c] = TRES[i];
                    TRES[i] = numero;
                }
            }
        }
    }
    public void mostrarC(){
        txtA3.setText(null);
        for(int c = 0;c < indice3;c++){
            txtA3.append("[" + c + "]-->" + TRES[c] + "\n");
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA1 = new javax.swing.JTextArea();
        btnMostrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModifcar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtA3 = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("VECTOR 1");

        btnGenerar.setText("GENERAR");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtA1.setColumns(20);
        txtA1.setRows(5);
        jScrollPane1.setViewportView(txtA1);

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModifcar.setText("MODIFICAR");
        btnModifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifcarActionPerformed(evt);
            }
        });

        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        jLabel2.setText("VECTOR 2");

        jLabel3.setText("VECTOR 3");

        txtA2.setColumns(20);
        txtA2.setRows(5);
        jScrollPane2.setViewportView(txtA2);

        txtA3.setColumns(20);
        txtA3.setRows(5);
        jScrollPane3.setViewportView(txtA3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscar)
                    .addComponent(btnGenerar)
                    .addComponent(btnMostrar)
                    .addComponent(btnModifcar)
                    .addComponent(btnOrdenar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBuscar, btnGenerar, btnModifcar, btnMostrar, btnOrdenar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifcar)
                        .addGap(14, 14, 14)
                        .addComponent(btnOrdenar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        UNO = new int[Integer.parseInt(JOptionPane.showInputDialog("CANTIDAD DE ELEMENTOS"))];
        indice1 = 0;
        generarVector();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        mostrarVector();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DOS = new int[UNO.length];
        indice2 = 0;
        int numero = Integer.parseInt(JOptionPane.showInputDialog("INGRESE VALOR A BUSCAR"));        
        if(buscarVector(numero)){
            mostrarPos(numero);
        }else{
            JOptionPane.showMessageDialog(null,"VALOR NO SE ENCONTRO","MENSAJE",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifcarActionPerformed
        int numero = Integer.parseInt(JOptionPane.showInputDialog("INGRESE VALOR A BUSCAR"));
        int valor = Integer.parseInt(JOptionPane.showInputDialog("LOS MODIFICARA POR"));
        if(buscarVector(numero)){
            modificarValor(valor);
        }else{
            JOptionPane.showMessageDialog(null,"VALOR NO SE ENCONTRO","MENSAJE",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnModifcarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        TRES = new int[UNO.length];
        indice3 = 0;
        moverC();
        ordenarC();
        mostrarC();
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ej1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ej1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnModifcar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtA1;
    private javax.swing.JTextArea txtA2;
    private javax.swing.JTextArea txtA3;
    // End of variables declaration//GEN-END:variables

}
