/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenfinal;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class Formulario extends javax.swing.JFrame {
    
    Paciente []pac;
    int indice;

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        this.setLocationRelativeTo(null);
        pac=new Paciente[5];
    }
    
    public boolean codigoRepetido(int cod)
    {
        boolean flag=false;
        for(int i=0;i<indice;i++)
        {
            if (pac[i].getCod()==cod)
                flag=true;
            else
                flag=false;
        }
        return flag;
    }
    
    public int buscar(int cod)
    {
        int pos=-1;
        for(int i=0;i<indice;i++)
        {
            if(pac[i].getCod()==cod)
            {
                pos=i;
                break;
            }             
        }
        return pos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRes = new javax.swing.JTextArea();
        txtNombre = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnPrueba = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXAMEN FINAL");

        jLabel1.setText("NOMBRE");

        txaRes.setColumns(20);
        txaRes.setRows(5);
        jScrollPane1.setViewportView(txaRes);

        btnRegistrar.setText("REGISTRAR PACIENTE");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR PACIENTE");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPrueba.setText("PRUEBA");
        btnPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActionPerformed(evt);
            }
        });

        btnListar.setText("LISTAR PACIENTES");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrueba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        int cod=0;
        boolean flag=true;
        
        if (indice<pac.length){
            do{
                cod=Utilitario.generarAleatorio(1000, 1999);
                flag=codigoRepetido(cod);
            }while(flag==true);
            String nom=txtNombre.getText();
            int edad=Utilitario.generarAleatorio(1, 30);
            String sexo=Utilitario.generarAleatorio();
            if(edad>=12)
            {
                if(sexo.equals("F"))
                {
                    pac[indice]=new Paciente(cod,nom,edad,sexo);
                    indice++;
                }
                else
                    Utilitario.mensaje("EL SEXO ES MASCULINO, NO SE REGISTRO");
            }
            else
                Utilitario.mensaje("MENOR DE EDAD, VISITE A SU MÉDICO");}
        else
            Utilitario.mensaje("NO SE PUEDE REGISTRAR MÁS PACIENTES");
        txtNombre.setText(null);
        txtNombre.requestFocus();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int pos=buscar(Integer.parseInt(Utilitario.ingreso("INGRESE CÓDIGO A BUSCAR")));
        if (pos!=-1)
        {
            txaRes.setText(null);
            txaRes.append("BUSQUEDA DEL PACIENTE\n");
            txaRes.append("-------------------------------------------\n");
            txaRes.append("CODIGO: "+pac[pos].getCod()+"\n");
            txaRes.append("NOMBRE: "+pac[pos].getNombre()+"\n");
            txaRes.append("EDAD: "+pac[pos].getEdad()+"\n");
            txaRes.append("SEXO: "+pac[pos].getSexo()+"\n");
            txaRes.append("PRUEBAS\n");
            for(int i=0;i<pac[pos].getIndice_p();i++)
            {
                txaRes.append("  --  "+pac[pos].getPrueba()[i]+"\n");
            } 
        }
        else
            Utilitario.mensaje("NO SE ENCONTRO AL PACIENTE");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        txaRes.setText(null);
        for(int i=0;i<indice;i++)
        {   
            txaRes.append("\nPACIENTE NRO. "+(i+1)+"\n");
            txaRes.append("   CODIGO: "+pac[i].getCod()+"\n");
            txaRes.append("   NOMBRE: "+pac[i].getNombre()+"\n");
            txaRes.append("   EDAD: "+pac[i].getEdad()+"\n");
            txaRes.append("   SEXO: "+pac[i].getSexo()+"\n"); 
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActionPerformed
        // TODO add your handling code here:
        int pos=buscar(Integer.parseInt(Utilitario.ingreso("INGRESE CÓDIGO A BUSCAR")));
        if (pos!=-1)
        {
            
            if(pac[pos].getIndice_p()<pac[pos].getPrueba().length)
            {
                int op=Integer.parseInt(Utilitario.ingreso("INGRESE TIPO DE PRUEBA"+
                "\n1. PRUEBA DE SANGRE\n2. PRUEBA DE ORINA"));
                switch (op){
                        case 1:
                            pac[pos].setPrueba(new P_Sangre().realizarPrueba());
                            Utilitario.mensaje("SE REALIZÓ LA PRUEBA DE SANGRE");
                            break;
                        case 2:
                            pac[pos].setPrueba(new P_Orina().realizarPrueba());
                            Utilitario.mensaje("SE REALIZÓ LA PRUEBA DE ORINA");
                            break;
                        default:
                            Utilitario.mensaje("ERROR!!! .. INGRESE LA OPCIÓN CORRECTA");}
            }
            else
                Utilitario.mensaje("NO SE PERMITEN MAS PRUEBAS");
        }
        else
            Utilitario.mensaje("NO SE ENCONTRO AL PACIENTE");
    }//GEN-LAST:event_btnPruebaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnPrueba;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaRes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
