/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio_2;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Formulario extends javax.swing.JFrame {
Persona []vector=new Persona[4];
int indice=0;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    public int Buscar(String bus){
        int pos=-1;
        for(int c=0;c<indice;c++){
            if(vector[c].getNombre().equals(bus)){
                pos=c;
            }
        }
        return pos;
    }
    public void MostrarEmpleado(){
        txtA.setText("EMPLEADOS\n");
        for(int c=0;c<indice;c++){
            if(vector[c].tipo.equals("EMPLEADO")){
                Empleado Em=(Empleado)(vector[c]);
                txtA.append("-----------------------------------\n");
                txtA.append("NOMBRE: "+Em.getNombre()+"\n");
                txtA.append("EDAD: "+Em.getEdad()+"\n");
                txtA.append("SALARIO: "+Em.getSalario()+"\n");
            }
        } 
    }
    public void MostrarEstudiante(){
        txtA.setText("ESTUDIANTES\n");
        for(int c=0;c<indice;c++){
            if(vector[c].tipo.equals("ESTUDIANTE")){
                Estudiante Es=(Estudiante)(vector[c]);
                txtA.append("-----------------------------------\n");
                txtA.append("NOMBRE: "+Es.getNombre()+"\n");
                txtA.append("EDAD: "+Es.getEdad()+"\n");
                txtA.append("CARRERA: "+Es.getCarrera()+"\n");
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnMostrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre:");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        jLabel2.setText("Edad:");

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR DATOS");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if(indice<vector.length){
            String nombre=txtNombre.getText().toUpperCase();
            String e=txtEdad.getText();
            if(nombre.equals("")!=true&&e.equals("")!=true){
                int Tipo=Integer.parseInt(JOptionPane.showInputDialog(null,"1. EMPLEADO\n2.ESTUDIANTE","ENTRADA",JOptionPane.QUESTION_MESSAGE));
                int edad=Integer.parseInt(e);
                switch(Tipo){
                    case 1:double salario=Double.parseDouble(JOptionPane.showInputDialog(null,"INSERTAR SALARIO","ENTRADA",JOptionPane.QUESTION_MESSAGE));
                            vector[indice]=new Empleado("EMPLEADO",nombre, edad, salario);
                            indice++;
                            break;
                    case 2:String carrera=JOptionPane.showInputDialog(null,"CARRERA","INFORMACION",JOptionPane.QUESTION_MESSAGE).toUpperCase();
                            vector[indice]=new Estudiante("ESTUDIANTE",nombre, edad, carrera);
                            indice++;
                            break;
                    default: JOptionPane.showMessageDialog(null,"RESPUESTA INCORRECTA","INFORMACION",JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"ESPACIOS VACIOS","INFORMACION",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"NO SE PUEDEN ALMACENAR MAS PERSONAS","INFORMACION",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        int Tipo=Integer.parseInt(JOptionPane.showInputDialog(null,"1. EMPLEADO\n2. ESTUDIANTE","ENTRADA",JOptionPane.QUESTION_MESSAGE));
        switch(Tipo){
            case 1:MostrarEmpleado();
                    break;
            case 2:MostrarEstudiante();
                    break;
            default: JOptionPane.showMessageDialog(null,"RESPUESTA INCORRECTA","INFORMACION",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int Tipo=Integer.parseInt(JOptionPane.showInputDialog(null,"1. EMPLEADO\n2.ESTUDIANTE","ENTRADA",JOptionPane.QUESTION_MESSAGE));
        switch(Tipo){
            case 1:
                String nom1=JOptionPane.showInputDialog(null,"INSERTAR NOMBRE A BUSCAR","INFORMACION",JOptionPane.QUESTION_MESSAGE).toUpperCase();
                int pos1=Buscar(nom1);
                if(pos1!=-1){
                    vector[pos1].modificarDatos();
                    MostrarEmpleado();
                }else{
                    JOptionPane.showMessageDialog(null,"EMPLEADO NO ENCONTRADO","INFORMACION",JOptionPane.WARNING_MESSAGE);
                }
                break;
            case 2:
                String nombre=JOptionPane.showInputDialog(null,"INSERTAR NOMBRE A BUSCAR","INFORMACION",JOptionPane.QUESTION_MESSAGE).toUpperCase();
                int pos2=Buscar(nombre);
                if(pos2!=-1){
                    vector[pos2].modificarDatos();
                    MostrarEstudiante();
                }else{
                    JOptionPane.showMessageDialog(null,"ESTUDIANTE NO ENCONTRADO","INFORMACION",JOptionPane.WARNING_MESSAGE);
                }
                break;
            default: JOptionPane.showMessageDialog(null,"RESPUESTA INCORRECTA","INFORMACION",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
