/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PARCIAL;

import javax.swing.JOptionPane;

/**
 *
 * @author jmgut
 */
public class Pregunta1 extends javax.swing.JFrame {
String vecA[]=new String [10];
int indiceA=0;
int vecB[]=new int [10],indiceB=0;
boolean x=false,y=false;
    /**
     * Creates new form TRENES
     */
    public Pregunta1() {
        initComponents();
    }
    public int GenerarNumeroDeAsiento(){
        int asi;
        do{
            asi=(int)(Math.random()*(20-1+1)+1);
        }while(asi%2!=0);
        return asi;
    }
    public void Eliminar(int pos){
        for(int j=pos;j<indiceB-1&&j<indiceA-1;j++){
            vecB[j]=vecB[j+1];
            vecA[j]=vecA[j+1];
        }
        String auxA[]=new String[vecA.length];
        int auxB[]=new int[vecB.length];
        for(int c=0;c<indiceB-1&&c<indiceA-1;c++){
            auxA[c]=vecA[c];
            auxB[c]=vecB[c];
        }
        vecA=auxA;
        vecB=auxB;
        indiceA--;
        indiceB--;
        JOptionPane.showMessageDialog(this, "El asiento fue eliminado");
    }
    public int Buscar(int veli){
        int pos=-1;
        for(int i=0;i<indiceA&&i<indiceB;i++){
            if(veli==vecB[i]){
                  pos=i;     
            }
        }
        return pos;
    }
    public void Ordenar(){
        for(int c=0;c<indiceB-1&&c<indiceA-1;c++){
            for(int i=c+1;i<indiceB&&c<indiceA;i++){
                if(vecB[i]<=vecB[c]){
                    int auxB=vecB[c];
                    vecB[c]=vecB[i];
                    vecB[i]=auxB;
                    String auxA=vecA[c];
                    vecA[c]=vecA[i];
                    vecA[i]=auxA;
                }
            }
        }
    }
    public void Mostrar(){
        txtPasajero.setText(null);
        for(int c=0;c<indiceA;c++){
            txtPasajero.append(vecA[c]+"\n");
        }
        txtAsiento.setText(null);
        for(int c=0;c<indiceB;c++){
            txtAsiento.append(vecB[c]+"\n");
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPasajero = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAsiento = new javax.swing.JTextArea();
        btnMostrar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("PASAJERO");

        jLabel3.setText("ASIENTO");

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        txtPasajero.setColumns(20);
        txtPasajero.setRows(5);
        jScrollPane1.setViewportView(txtPasajero);

        txtAsiento.setColumns(20);
        txtAsiento.setRows(5);
        jScrollPane2.setViewportView(txtAsiento);

        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRegistrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMostrar)
                                    .addComponent(btnEliminar)
                                    .addComponent(btnOrdenar))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addGap(9, 9, 9)
                        .addComponent(btnOrdenar))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String tex=txtNombre.getText();
        tex=tex.trim();
        if(tex.compareTo("")!=0){
            if(indiceB<vecB.length&&indiceA<vecA.length){
                String nom=txtNombre.getText();
                vecA[indiceA]=nom.toUpperCase();
                x=true;
                indiceA++;
                if(indiceB==0){
                    y=true; 
                    vecB[indiceB]=GenerarNumeroDeAsiento();
                    indiceB++;
                }else{
                    y=true;
                    vecB[indiceB]=GenerarNumeroDeAsiento();
                    for(int i=0;i<indiceB;i++){
                        if(vecB[indiceB]==vecB[i]){
                            do{
                                vecB[indiceB]=GenerarNumeroDeAsiento();
                            }while(vecB[indiceB]==vecB[i]);
                            i=-1;
                        }
                    }
                    indiceB++;
                }
                txtNombre.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this,"ASIENTOS LLENOS","ALERTA", JOptionPane.WARNING_MESSAGE);
            }  
        }else{JOptionPane.showMessageDialog(this,"INGRESE PASAJERO");
            
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if(x==true&&y==true){
            if(indiceB>0&&indiceA>0){
                Mostrar();
            }else{
                JOptionPane.showMessageDialog(this,"TREN VACIO","ALERTA", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"TREN VACIO","ALERTA", JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(x==true&&y==true){
            if(indiceB>0&&indiceA>0){
                int veli=Integer.parseInt(JOptionPane.showInputDialog(this,"ASIENTO BUSCADO","Entrada",JOptionPane.QUESTION_MESSAGE));
                int pos=Buscar(veli);
                if(pos>=0){
                    Eliminar(pos);
                    Mostrar();
                }else{
                    JOptionPane.showMessageDialog(this,"EL ASIENTO NO EXISTE","ALERTA", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this,"TREN VACIO","ALERTA", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"TREN VACIO","ALERTA", JOptionPane.WARNING_MESSAGE);        
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        if(x==true&&y==true){
            Ordenar();
            Mostrar();
        }else{
            JOptionPane.showMessageDialog(this,"TREN VACIO","ALERTA", JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAsiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtPasajero;
    // End of variables declaration//GEN-END:variables
}
