/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_5;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Frm_4 extends javax.swing.JFrame {
int numeros;
int indice=0;
int vec[]=new int[25];

    /**
     * Creates new form Frm_5
     */
    public Frm_4() {
        initComponents();
    }
    public void Ingresar(){
        if(indice<vec.length){
            vec[indice]=numeros;
            indice++;
        }else{
            JOptionPane.showMessageDialog(this,"El Vector esta lleno !!!!!!!!");
        }
    }
    public int qCeros(){
        int cCeros=0;
        for(int c=0;c<indice;c++){
            if(vec[c]==0){
                cCeros++;
            }
        }
        return cCeros;
    }
    public int qNegativos(){
        int cNeg=0;
        for(int c=0;c<indice;c++){
            if(vec[c]<0){
                cNeg++;
            }
        }
        return cNeg;
    }
    public int qPositivos(){
        int cPos=0;
        for(int c=0;c<indice;c++){
            if(vec[c]>0){
                cPos++;
            }
        }
        return cPos;
    }
    public int SumaNegativos(){
        int sumaNeg=0;
        for(int c=0;c<indice;c++){
            if(vec[c]<0){
                sumaNeg-=vec[c];
            }
        }
        return sumaNeg;
    }
    public int SumaPositivos(){
        int sumaPos=0;
        for(int c=0;c<indice;c++){
            if(vec[c]>0){
                sumaPos+=vec[c];
            }
        }
        return sumaPos;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCeros = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        btnNegativos = new javax.swing.JButton();
        btnPositivos = new javax.swing.JButton();
        btnSumNeg = new javax.swing.JButton();
        btnSumPos = new javax.swing.JButton();
        txtqPos = new javax.swing.JTextField();
        txtqNeg = new javax.swing.JTextField();
        txtsuPos = new javax.swing.JTextField();
        txtqCeros = new javax.swing.JTextField();
        txtsuNeg = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCeros.setText("CEROS");
        btnCeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerosActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar Número:");

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        btnNegativos.setText("NEGATIVOS");
        btnNegativos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegativosActionPerformed(evt);
            }
        });

        btnPositivos.setText("POSITIVOS");
        btnPositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositivosActionPerformed(evt);
            }
        });

        btnSumNeg.setText("SUMATORIA NEGATIVOS");
        btnSumNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumNegActionPerformed(evt);
            }
        });

        btnSumPos.setText("SUMATORIA POSITIVOS");
        btnSumPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumPosActionPerformed(evt);
            }
        });

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSumNeg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCeros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNegativos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPositivos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSumPos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtqCeros)
                            .addComponent(txtqNeg)
                            .addComponent(txtqPos)
                            .addComponent(txtsuNeg)
                            .addComponent(txtsuPos)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIngresar)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtqCeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCeros, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtqNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNegativos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtqPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPositivos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumNeg)
                    .addComponent(txtsuNeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumPos)
                    .addComponent(txtsuPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String tex=txtNum.getText();
        if(tex.compareTo("")!=0){
            numeros=Integer.parseInt(txtNum.getText());
            Ingresar();
        }else{
            JOptionPane.showMessageDialog(this,"No se introdujo un valor","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnCerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerosActionPerformed
        int qCeros=qCeros();
        txtqCeros.setText(String.valueOf(qCeros));
    }//GEN-LAST:event_btnCerosActionPerformed

    private void btnNegativosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegativosActionPerformed
        int qNeg=qNegativos();
        txtqNeg.setText(String.valueOf(qNeg));
    }//GEN-LAST:event_btnNegativosActionPerformed

    private void btnPositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositivosActionPerformed
        int qPos=qPositivos();
        txtqPos.setText(String.valueOf(qPos));
    }//GEN-LAST:event_btnPositivosActionPerformed

    private void btnSumNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumNegActionPerformed
        int sumaNeg=SumaNegativos();
        if(sumaNeg==0){
            txtsuNeg.setText(String.valueOf(sumaNeg));
        }else{
            txtsuNeg.setText("-"+sumaNeg);
        }
    }//GEN-LAST:event_btnSumNegActionPerformed

    private void btnSumPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumPosActionPerformed
        int sumaPos=SumaPositivos();
        txtsuPos.setText(String.valueOf(sumaPos));
    }//GEN-LAST:event_btnSumPosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCeros;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNegativos;
    private javax.swing.JButton btnPositivos;
    private javax.swing.JButton btnSumNeg;
    private javax.swing.JButton btnSumPos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextField txtqCeros;
    private javax.swing.JTextField txtqNeg;
    private javax.swing.JTextField txtqPos;
    private javax.swing.JTextField txtsuNeg;
    private javax.swing.JTextField txtsuPos;
    // End of variables declaration//GEN-END:variables
}
