/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_5;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Frm_3 extends javax.swing.JFrame {
int vec[]=new int[20];
int indice;
boolean x=false;
    /**
     * Creates new form Frm_3
     */
    public Frm_3() {
        initComponents();
    }
    public void Poblar(){
        indice=0;
        for(int c=0;c<vec.length;c++){
            vec[c]=(int)(Math.random()*(50-0+1)+0);
            if(c>0){
                for(int x=0;x<indice;x++){
                    while(vec[x]==vec[c]){
                        vec[c]=(int)(Math.random()*(50-0+1)+0);
                    }
                } 
            }
            indice++;
        }
    }
    public void ElementMayor(){
        int nMa=0,pos=0;
        for(int i=0;i<vec.length;i++){
            if(nMa<vec[i]){
                nMa=vec[i];
                pos=i;
            }
        }
        txtA.append("\n El numero mayor es: "+nMa+"  en la posicion "+pos);
    }
    public void ElementMenor(){
        int nMe=9999999,pos=0;
        for(int i=0;i<vec.length;i++){
            if(nMe>vec[i]){
                nMe=vec[i];
                pos=i;
            }
        }
        txtA.append("\n El numero menor es: "+nMe+"  en la posicion "+pos);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPoblar = new javax.swing.JButton();
        btnElementoMenor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        btnElementoMayor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPoblar.setText("POBLAR");
        btnPoblar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoblarActionPerformed(evt);
            }
        });

        btnElementoMenor.setText("ELEMENTO MENOR");
        btnElementoMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElementoMenorActionPerformed(evt);
            }
        });

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnElementoMayor.setText("ELEMENTO MAYOR");
        btnElementoMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElementoMayorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPoblar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnElementoMayor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnElementoMenor)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPoblar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElementoMayor)
                    .addComponent(btnElementoMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPoblarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoblarActionPerformed
        x=true;
        Poblar();
        txtA.setText(null);
        for(int j=0;j<vec.length;j++){
            if(j<vec.length-1){
                txtA.append(vec[j]+"; ");
            }else{
                txtA.append(vec[j]+"");
            }
        }
    }//GEN-LAST:event_btnPoblarActionPerformed

    private void btnElementoMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElementoMayorActionPerformed
        if(x==true){
            ElementMayor();
        }else{
            JOptionPane.showMessageDialog(this,"NO SE POBLO EL VECTOR!!","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnElementoMayorActionPerformed

    private void btnElementoMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElementoMenorActionPerformed
        if(x==true){
            ElementMenor();
        }else{
            JOptionPane.showMessageDialog(this,"NO SE POBLO EL VECTOR!!","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnElementoMenorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElementoMayor;
    private javax.swing.JButton btnElementoMenor;
    private javax.swing.JButton btnPoblar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    // End of variables declaration//GEN-END:variables
}
