/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio_1;

import javax.swing.JOptionPane;

/**
 *
 * @author JM Gutierrez
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }
    public void MostrarPlaneta(Astros A){
        txtA.setText(null);
        txtA.append(A.getNombre()+"\n");
        txtA.append("Masa del cuerpo: "+A.getMCuerpo()+"\n");
        txtA.append("Diametro Medio: "+A.getDiaMe()+" km.\n");
        txtA.append("Periodo de rotacion: "+A.getPerRot()+" horas\n");
        txtA.append("Periodo de traslacion: "+A.getPerTras()+" dias terranos\n");
        txtA.append("Cantidad de lunas: "+A.getqLunas()+" Lunas\n");
        txtA.append("Distacion media al sol: "+A.getDistanciaMediaSol()+" Años luz\n");
        txtA.append("Excentricidad de la orbita: "+A.getExcent()+"\n");
    }
    public void MostrarSol(Sol A){
        txtA.setText(null);
        txtA.append(A.getNombre()+"\n");
        txtA.append("Masa del cuerpo: "+A.getMCuerpo()+"\n");
        txtA.append("Diametro Medio: "+A.getDiaMe()+" millones km.\n");
        txtA.append("Periodo de rotacion: "+A.getPerRot()+" dias\n");
        txtA.append("Periodo de traslacion: "+A.getPerTras()+" millones de años\n");
        txtA.append("Cantidad de lunas: "+A.getqLunas()+" Lunas\n");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        btnMercurio = new javax.swing.JButton();
        btnVenus = new javax.swing.JButton();
        btnTierra = new javax.swing.JButton();
        btnMarte = new javax.swing.JButton();
        btnJupiter = new javax.swing.JButton();
        btnSaturno = new javax.swing.JButton();
        btnUrano = new javax.swing.JButton();
        btnNeptuno = new javax.swing.JButton();
        btnSol = new javax.swing.JButton();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnMercurio.setText("MERCURIO");
        btnMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMercurioActionPerformed(evt);
            }
        });

        btnVenus.setText("VENUS");
        btnVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenusActionPerformed(evt);
            }
        });

        btnTierra.setText("LA TIERRA");
        btnTierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTierraActionPerformed(evt);
            }
        });

        btnMarte.setText("MARTE");
        btnMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarteActionPerformed(evt);
            }
        });

        btnJupiter.setText("JUPITER");
        btnJupiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJupiterActionPerformed(evt);
            }
        });

        btnSaturno.setText("SATURNO");
        btnSaturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaturnoActionPerformed(evt);
            }
        });

        btnUrano.setText("URANO");
        btnUrano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUranoActionPerformed(evt);
            }
        });

        btnNeptuno.setText("NEPTUNO");
        btnNeptuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeptunoActionPerformed(evt);
            }
        });

        btnSol.setText("SOL");
        btnSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnMercurio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVenus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTierra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMarte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnJupiter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaturno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUrano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNeptuno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnJupiter, btnMarte, btnMercurio, btnNeptuno, btnSaturno, btnTierra, btnUrano, btnVenus});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMercurio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVenus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTierra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMarte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJupiter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSaturno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUrano)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNeptuno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSol))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMercurioActionPerformed
        MostrarPlaneta(new Mercurio("Mercuro", "1,98E3",4879.4, 1408, 88, 0, 0.2056, 57910000));
    }//GEN-LAST:event_btnMercurioActionPerformed

    private void btnVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenusActionPerformed
        MostrarPlaneta(new Venus("Venus", "4,83E24",12104, 5832, 224, 0, 0.068, 108200000));
    }//GEN-LAST:event_btnVenusActionPerformed

    private void btnTierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTierraActionPerformed
        MostrarPlaneta(new LaTierra("Tierra", "5,98E24",12742, 24, 365, 1, 0.0167, 146600000));
    }//GEN-LAST:event_btnTierraActionPerformed

    private void btnMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarteActionPerformed
       MostrarPlaneta(new Marte("Marte", "6,40E23",6779, 25, 686, 2, 0.0934, 227940000));
    }//GEN-LAST:event_btnMarteActionPerformed

    private void btnJupiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJupiterActionPerformed
        MostrarPlaneta(new Jupiter("Jupiter", "1,90E27",139820, 10, 4329, 79, 0.0483, 778330000));
    }//GEN-LAST:event_btnJupiterActionPerformed

    private void btnSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaturnoActionPerformed
        MostrarPlaneta(new Saturno("Saturno", "5,98E26",116460, 11, 10752, 82, 0.0560, 1429400000));
    }//GEN-LAST:event_btnSaturnoActionPerformed

    private void btnUranoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUranoActionPerformed
        MostrarPlaneta(new Urano("Urano", "8,67E25",50724, 17, 30667, 27, 0.0461, 287099000));
    }//GEN-LAST:event_btnUranoActionPerformed

    private void btnNeptunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeptunoActionPerformed
        MostrarPlaneta(new Neptuno("Neptuno", "1,05E26",49244, 16, 60140, 14, 0.0097, 450430000));
    }//GEN-LAST:event_btnNeptunoActionPerformed

    private void btnSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolActionPerformed
        MostrarSol(new Sol("Sol","6,96E8", 1.3927 , 27, 230, 0));
    }//GEN-LAST:event_btnSolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJupiter;
    private javax.swing.JButton btnMarte;
    private javax.swing.JButton btnMercurio;
    private javax.swing.JButton btnNeptuno;
    private javax.swing.JButton btnSaturno;
    private javax.swing.JButton btnSol;
    private javax.swing.JButton btnTierra;
    private javax.swing.JButton btnUrano;
    private javax.swing.JButton btnVenus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea txtA;
    // End of variables declaration//GEN-END:variables
}
