/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PARCIAL;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Pregunta_1 extends javax.swing.JFrame {
int FIB[];
int ord[];
int indice;
int indice1;
boolean x,y;
    /**
     * Creates new form Pregunta_1
     */
    public Pregunta_1() {
        initComponents();
    }
    public void GenerarFib(){
        indice=0;
        x=true;
        for(int c=0;c<FIB.length;c++){
            if(c<2){
                FIB[c]=c;
            }else{
                FIB[c]=FIB[c-1]+FIB[c-2];
            }
            indice++;
        }
    }
    public void MostrarFib(){
        y=true;
        txtAfib.setText(null);
        for(int i=0;i<FIB.length;i++){
            txtAfib.append("FIB ["+i+"]"+"--->"+FIB[i]+"\n");
        }
    }
    public void OrdenarFib(){
        indice1=0;
        int pos;
        for(int i=0;i<indice;i++){
            if(FIB[i]%2!=0){
                ord[indice1]=FIB[i];
                indice1++;
            }
        }
        pos=indice1;
        for(int i=0;i<indice1-1;i++){
            for(int j=i+1;j<indice1;j++){
                if(ord[i]>=ord[j]){
                    int aux=ord[i];
                    ord[i]=ord[j];
                    ord[j]=aux;
                }
            }
        }
        for(int i=0;i<indice;i++){
            if(FIB[i]%2==0){
                ord[indice1]=FIB[i];
                indice1++;
            }
        }
        for(int i=pos;i<indice1-1;i++){
            for(int j=i+1;j<indice1;j++){
                if(ord[i]>=ord[j]){
                    int aux=ord[i];
                    ord[i]=ord[j];
                    ord[j]=aux;
                }
            }
        }
    }
    public void MostrarOrd(){
        txtAOrd.setText(null);
        for(int i=0;i<ord.length;i++){
            txtAOrd.append("ORD ["+i+"]"+"--->"+ord[i]+"\n");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEjecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAfib = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAOrd = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEjecutar.setText("EJECUTAR");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        txtAfib.setColumns(20);
        txtAfib.setRows(5);
        jScrollPane1.setViewportView(txtAfib);

        txtAOrd.setColumns(20);
        txtAOrd.setRows(5);
        jScrollPane2.setViewportView(txtAOrd);

        jLabel1.setText("FIBONACCI");

        jLabel2.setText("ORDENADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEjecutar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        int tamaño=Integer.parseInt(JOptionPane.showInputDialog(this,"CANTIDAD DE ELEMENTOS","Entrada",JOptionPane.QUESTION_MESSAGE));
        FIB=new int[tamaño];
        ord=new int[tamaño];
        GenerarFib();
        MostrarFib();
        OrdenarFib();
        MostrarOrd();
    }//GEN-LAST:event_btnEjecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAOrd;
    private javax.swing.JTextArea txtAfib;
    // End of variables declaration//GEN-END:variables
}
