/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usmp.aedi.semana10;

import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void mostrarPadre(Padre p)
    {
        txaRes.setText(null);
        String msj=p.verMensaje();
        txaRes.append(msj+"\n");
        txaRes.append("     NOMBRE: "+p.getNombre()+"\n");
        txaRes.append("     EDAD: "+p.getEdad()+"\n");
        txaRes.append("     SUELDO: "+p.getSueldo()+"\n");
    }

    public void mostrarHija(Hija h)
    {
        txaRes.setText(null);
        String msj=h.verMensaje();
        txaRes.append(msj+"\n");
        txaRes.append("     NOMBRE: "+h.getNombre()+"\n");
        txaRes.append("     EDAD: "+h.getEdad()+"\n");
        txaRes.append("     SUELDO: "+h.getSueldo()+"\n");
        txaRes.append("     CARRERA: "+h.getCarrera()+"\n");
    }
    
    public void mostrarNieta(Nieta n)
    {
        String msj=n.verMensaje();
        txaRes.append(msj+"\n");
        txaRes.append("     NOMBRE: "+n.getNombre()+"\n");
        txaRes.append("     EDAD: "+n.getEdad()+"\n");
        txaRes.append("     MUSICA: "+n.getMusica()+"\n");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPadre = new javax.swing.JButton();
        btnHija = new javax.swing.JButton();
        btnNieta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejericio10-2");

        btnPadre.setText("PADRE");
        btnPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPadreActionPerformed(evt);
            }
        });

        btnHija.setText("HIJA");
        btnHija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHijaActionPerformed(evt);
            }
        });

        btnNieta.setText("NIETA");
        btnNieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNietaActionPerformed(evt);
            }
        });

        txaRes.setColumns(20);
        txaRes.setRows(5);
        jScrollPane1.setViewportView(txaRes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHija, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPadre)
                .addGap(4, 4, 4)
                .addComponent(btnHija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNieta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPadreActionPerformed
        // TODO add your handling code here:
        Padre Padre1=new Padre("Padre 1",50,1500);
        mostrarPadre(Padre1);
    }//GEN-LAST:event_btnPadreActionPerformed

    private void btnHijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHijaActionPerformed
        // TODO add your handling code here:
        Hija Hija1=new Hija("Hija 1",26,500,"Sistemas");
        mostrarHija(Hija1);
    }//GEN-LAST:event_btnHijaActionPerformed

    private void btnNietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNietaActionPerformed
        // TODO add your handling code here:
        txaRes.setText(null);
        Nieta Nieta1=new Nieta("Nieta 1",10,"POP");
        mostrarNieta(Nieta1);
        JOptionPane.showMessageDialog(null,"LA NIETA CUMPLIO AÑOS","IMPORTANTE",JOptionPane.INFORMATION_MESSAGE);
        Nieta1.cumplirAños();
        mostrarNieta(Nieta1);
    }//GEN-LAST:event_btnNietaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHija;
    private javax.swing.JButton btnNieta;
    private javax.swing.JButton btnPadre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaRes;
    // End of variables declaration//GEN-END:variables
}
