/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejecicio_1;

/**
 *
 * @author jmgut
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    public void imprimirAtributosComunes(Persona x) {

    }

    public void imprimirAtributosEstudiante(Estudiante x) {
        txtA.setText(null);
        txtA.append("NOMBRE: " + x.getNombre() + "\n");
        txtA.append("APELLIDO: " + x.getApellido() + "\n");
        txtA.append("GENERO: " + x.getGenero() + "\n");
        txtA.append("DNI: " + x.getDni() + "\n");
        txtA.append("CARRERA: " + x.getCarrera() + "\n");
        txtA.append("CREDITOS: " + x.getCreaditos() + "\n");
        txtA.append("PENSION: " + x.calcular() + "\n");
    }

    public void imprimirAtributosAdministrativo(Administrativo x) {
        txtA.setText(null);
        txtA.append("NOMBRE: " + x.getNombre() + "\n");
        txtA.append("APELLIDO: " + x.getApellido() + "\n");
        txtA.append("GENERO: " + x.getGenero() + "\n");
        txtA.append("DNI: " + x.getDni() + "\n");
        txtA.append("AREA: " + x.getArea() + "\n");
        txtA.append("HORAS TRABAJADAS: " + x.getHorastrabajadas() + "\n");
        txtA.append("SUELDO POR HORA: " + x.getSueldoporhora() + "\n");
        txtA.append("SALARIO: " + x.calcular() + "\n");
    }

    public void imprimirAtributosDocente(Docente x) {
        txtA.setText(null);
        txtA.append("NOMBRE: " + x.getNombre() + "\n");
        txtA.append("APELLIDO: " + x.getApellido() + "\n");
        txtA.append("GENERO: " + x.getGenero() + "\n");
        txtA.append("DNI: " + x.getDni() + "\n");
        txtA.append("TIPO: " + x.getTipo() + "\n");
        txtA.append("HORAS: " + x.getHoras() + "\n");
        txtA.append("GRADO ACEDEMICO: " + x.getGradoacademico() + "\n");
        txtA.append("PAGO: " + x.calcular() + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnEstudiante = new javax.swing.JButton();
        btnAdministrativo = new javax.swing.JButton();
        btnDocente = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("USMP");

        btnEstudiante.setText("ESTUDIANTE");
        btnEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudianteActionPerformed(evt);
            }
        });

        btnAdministrativo.setText("ADMINISTRATIVO");
        btnAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrativoActionPerformed(evt);
            }
        });

        btnDocente.setText("DOCENTE");
        btnDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdministrativo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(btnEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel2)
                        .addContainerGap(116, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdministrativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDocente)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudianteActionPerformed
        imprimirAtributosEstudiante(new Estudiante());
    }//GEN-LAST:event_btnEstudianteActionPerformed

    private void btnAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrativoActionPerformed
        int t = Integer.parseInt(Utilitario.getMensaje("1.Adminitrativo sin HE\n2.Administrativo con HE"));
        switch (t) {
            case 1://Administrativo_sin_HE AsHe=new Administrativo_sin_HE();
                imprimirAtributosAdministrativo(new Administrativo_sin_HE());
                break;
            case 2://Administrativo_con_HE AcHe=new Administrativo_con_HE();
                String nombre = Utilitario.getMensaje("INGRESAR NOMBRE").toUpperCase();
                String apellido = Utilitario.getMensaje("INGRESAR APELLIDO".toUpperCase());
                String genero = Utilitario.getMensaje("INGRESAR GENERO").toUpperCase();
                int dni = Integer.parseInt(Utilitario.getMensaje("INGRESAR DNI"));
                String area = Utilitario.getMensaje("INGRESE AREA").toUpperCase();
                int c = Integer.parseInt(Utilitario.getMensaje("INGRESE HORAS"));
                int horasextras = 0;
                int horastrabajadas = 0;
                if (c >= 40) {
                    horastrabajadas = c;
                    if (horastrabajadas > 40) {
                        horasextras = horastrabajadas - 40;
                    } else {
                        horasextras = 0;
                    }
                } else {
                    Utilitario.setMensajeError("Las horas trabajadas tiene que ser\nmayores que 40");
                }
                double sueldoporhora = Integer.parseInt(Utilitario.getMensaje("INGRESE SUELDO POR HORA"));
                imprimirAtributosAdministrativo(new Administrativo_con_HE(horasextras, area, horastrabajadas, sueldoporhora, nombre, apellido, genero, dni));
                break;
            default:
                Utilitario.setMensajeError("LA RESPUESTA NO CONCUERDA CON LAS ALTERNATIVAS");
        }
    }//GEN-LAST:event_btnAdministrativoActionPerformed

    private void btnDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteActionPerformed
        imprimirAtributosDocente(new Docente());
    }//GEN-LAST:event_btnDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrativo;
    private javax.swing.JButton btnDocente;
    private javax.swing.JButton btnEstudiante;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtA;
    // End of variables declaration//GEN-END:variables
}
