/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recuperacion;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Pregunta_2 extends javax.swing.JFrame {
String curso[]=new String[5];
int notas[]=new int[5];
int indice1=0;
int indice2=0;
boolean x=false;
    /**
     * Creates new form Pregunta_21
     */
    public Pregunta_2() {
        initComponents();
    }
    public void Agregar(String mat){
        x=true;
        curso[indice1]=mat.toUpperCase();
        indice1++;
        notas[indice2]=GenerarNota();
        indice2++;
    }
    public int GenerarNota(){
        int not=(int)(Math.random()*(20-0+1)+0);
        return not;
    }
    public void Mostrar(){
        txtA.setText(null);
        for(int i=0;i<indice1&&i<indice2;i++){
            txtA.append(curso[i]+"----"+notas[i]+"\n");
        }
    }
    public int Buscar(String teli){
        int pos=-1;
        for(int i=0;i<indice1&&i<indice2;i++){
            if(teli.compareTo(curso[i])==0){
                  pos=i;     
            }
        }
        return pos;
    }
    public void Eliminar(int pos){
        for(int j=pos;j<indice1-1;j++){
            curso[j]=curso[j+1];
            notas[j]=notas[j+1];
        }
        indice1--;
        indice2--;
        String auxA[]=new String[curso.length];
        int auxB[]=new int[notas.length];
        for(int c=0;c<indice1;c++){
            auxA[c]=curso[c];
            auxB[c]=notas[c];
        }
        curso=auxA;
        notas=auxB;
        
        JOptionPane.showMessageDialog(this, "El curso fue eliminado");
    }
    public void Promediar(){
        int suma=0;
        double prom;
        for(int i=0;i<indice1;i++){
            suma+=notas[i];
        }
        prom=suma*1.0/indice1;
        prom=Math.round(prom*100.0)/100.0;
        JOptionPane.showMessageDialog(this, "EL PROMEDIO ES: "+prom);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCurso = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();
        btnProm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnProm.setText("CALCULAR PROMEDIO");
        btnProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromActionPerformed(evt);
            }
        });

        jLabel1.setText("CURSO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregar))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String mat=txtCurso.getText();
        if(mat.compareTo("")!=0){
            if(indice1<curso.length&&indice2<notas.length){
                Agregar(mat);
                Mostrar();
            }else{
                JOptionPane.showMessageDialog(this,"EXCEDE DE LOS 5 CURSOS");
            }
        }else{
            JOptionPane.showMessageDialog(this,"NO INGRESO DATOS","ALERTA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String teli=JOptionPane.showInputDialog(this,"INGRESE CURSO","Entrada",JOptionPane.QUESTION_MESSAGE);
        if(teli.compareTo("")!=0){
            teli=teli.toUpperCase();
            int pos=Buscar(teli);
            if(pos>=0){
                Eliminar(pos);
                Mostrar();
            }else{
                JOptionPane.showMessageDialog(this,"CURSO NO ENCONTRADO","ALERTA", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this,"CASILLA VACIA","ALERTA", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromActionPerformed
        if(x==true){
            Promediar();
        }else{
            JOptionPane.showMessageDialog(this,"NOTAS VACIAS","ALERTA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnProm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtCurso;
    // End of variables declaration//GEN-END:variables
}
