/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package usmp.aedi.repaso;
import javax.swing.JOptionPane;
//JOptionPane.showInputDialog(this,"INGRESE AVERIA DEL CARRO").toUpperCase();
//JOptionPane.showMessageDialog(null,"TALLER DESOCUPADO!!!","IMPORTANTE",JOptionPane.WARNING_MESSAGE);
/**
 *
 * @author Alumno
 */
public class Ejemplo022 extends javax.swing.JFrame {
    
    /**
     * Creates new form Ejemplo022
     */
    public Ejemplo022() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaRes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIESTA");

        btnIngreso.setText("INICIAR INGRESO");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });

        txaRes.setColumns(15);
        txaRes.setRows(5);
        jScrollPane1.setViewportView(txaRes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                    .addComponent(btnIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIngreso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        // TODO add your handling code here:
        int edad,c_personas=0,c_hombres=0,c_mujeres=0;
        int suma_eh=0,suma_em=0,menor=999;
        String sexo;
        txaRes.setText(null);
        do
        {
            edad=Integer.parseInt(JOptionPane.showInputDialog(this,"INGRESE EDAD"));
            if(edad>=18)
            {
                sexo=JOptionPane.showInputDialog(this,"INGRESE SEXO").toUpperCase();
                
                c_personas=c_personas+1;
                
                if(sexo.equals("M"))
                {
                    c_hombres=c_hombres+1;
                    suma_eh=suma_eh+edad;
                }
                else
                {
                    c_mujeres=c_mujeres+1;
                    suma_em=suma_em+edad;
                }
                
                if(edad<menor)
                    menor=edad;
                
                txaRes.append(edad+" --- "+sexo+"\n");
            }
            else if(edad!=0)
                JOptionPane.showMessageDialog(null,"NO INGRESA - MENOR DE EDAD!!!",
                        "IMPORTANTE",JOptionPane.WARNING_MESSAGE);                    
        }while(edad!=0);
        
        txaRes.append("PERSONAS EN LA FIESTA: "+c_personas+"\n");
        txaRes.append("HOMBRES EN LA FIESTA: "+c_hombres+"\n");
        txaRes.append("MUJERES EN LA FIESTA: "+c_mujeres+"\n");
        txaRes.append("PROMEDIO DE EDAD HOMBRES: "+(suma_eh/c_hombres)+"\n");
        txaRes.append("PROMEDIO DE EDAD MUJERES: "+(suma_em/c_mujeres)+"\n");
        txaRes.append("PERSONA MAS JOVEN EN LA FIESTA: "+menor+"\n");
    }//GEN-LAST:event_btnIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo022.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo022.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo022.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo022.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo022().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaRes;
    // End of variables declaration//GEN-END:variables
}
