/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio_4;

import javax.swing.JOptionPane;

/**
 *
 * @author JM Gutierrez
 */
public class Interfaz extends javax.swing.JFrame {
Factura vecFac[]= new Factura [999999];
Pedido vecPed[]=new Pedido[999999];
CV vecCV[]=new CV[999999];
int indFac=0;
int indPed=0;
int indCon=0;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
    }
    public String Fecha(){
        int dia=Integer.parseInt(JOptionPane.showInputDialog(null,"INGRESAR DIA"));
        String mes=JOptionPane.showInputDialog(null,"INGRESAR NOMBRE DEL MES").toUpperCase();
        int año=Integer.parseInt(JOptionPane.showInputDialog(null,"INGRESAR AÑO"));
        return String.valueOf(dia)+" de "+mes+" del "+String.valueOf(año);
    }
    public void MostrarFactura(){
        txtA.setText("FACTURAS\n");
        for(int c=0;c<indFac;c++){
            txtA.append("ID: "+c+"\n");
            txtA.append("Emisor: "+vecFac[c].getEmisor()+"\n");
            txtA.append("Fecha: "+vecFac[c].getFecha()+"\n");
            txtA.append("Forma de pago: "+vecFac[c].getFormaPago()+"\n");
            txtA.append("Producto: "+vecFac[c].getProducto()+"\n");
            txtA.append("Precio: "+vecFac[c].getPrecio()+"\n");
            txtA.append("-------------------------------------------------\n");
        }
    }
    public void MostrarPedido(){
        txtA.setText("PEDIDOS\n");
        for(int c=0;c<indPed;c++){
            txtA.append("ID: "+c+"\n");
            txtA.append("Emisor: "+vecPed[c].getEmisor()+"\n");
            txtA.append("Fecha de Emision: "+vecPed[c].getFecha()+"\n");
            txtA.append("Fecha de Entrega: "+vecPed[c].getFechaEnt()+"\n");
            txtA.append("Telefono: "+vecPed[c].getTelefono()+"\n");
            txtA.append("Producto: "+vecPed[c].getProducto()+"\n");
            txtA.append("Precio: "+vecPed[c].getPrecio()+"\n");
            txtA.append("Tipo de pedido: "+vecPed[c].getTipoPedido()+"\n");
            txtA.append("-------------------------------------------------\n");
        }
    }
    public void MostrarCV(){
        txtA.setText("CONTRATOS\n");
        for(int c=0;c<indCon;c++){
            txtA.append("ID: "+c+"\n");
            txtA.append("Emisor: "+vecCV[c].getEmisor()+"\n");
            txtA.append("Fecha: "+vecCV[c].getFecha()+"\n");
            txtA.append("Razon social: "+vecCV[c].getRSocial()+"\n");
            txtA.append("Pais: "+vecCV[c].getPais()+"\n");
            txtA.append("Carrera: "+vecCV[c].getCarrera()+"\n");
            txtA.append("Universidad: "+vecCV[c].getEscuela()+"\n");
            txtA.append("Especialidad: "+vecCV[c].getEspecialidad()+"\n");
            txtA.append("-------------------------------------------------\n");
        }
    }
    public boolean CambiarPedido(int pos){
        boolean x=false;
        for(int i=0;i<indPed;i++){
            if(pos==i){
                vecPed[i]=new PedidoUrgente(vecPed[i].getFecha(),Fecha(),vecPed[i].getTelefono());
                x=true;
            }
        }
        return x;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboDoc = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        btnDatos = new javax.swing.JButton();
        btnCambiarPedido = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura", "Pedido", "Contrato" }));

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        jLabel2.setText("T. documento:");

        btnDatos.setText("Ingresar Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnCambiarPedido.setText("Cambiar Tipo de Pedido");
        btnCambiarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPedidoActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCambiarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCambiarPedido)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        int doc=cboDoc.getSelectedIndex();
        switch(doc){
            case 0: String fPago=JOptionPane.showInputDialog(null,"1.Al credito\n2.Al Contado");
                    if((fPago.toUpperCase()).compareTo("AL CREDITO")!=0&&(fPago.toUpperCase()).compareTo("AL CONTADO")!=0){
                        JOptionPane.showMessageDialog(null,"Esta no es un forma de pago aceptada","ERROR",JOptionPane.WARNING_MESSAGE);
                    }else{
                        vecFac[indFac]=new Factura(Fecha(),fPago);
                        indFac++;
                    }
                    break;
            case 1: String t=JOptionPane.showInputDialog(null,"INGRESAR TELEFONO");
                    if(t.length()!=9){
                            JOptionPane.showMessageDialog(null,"El numero debe tener 9 digitos","ERROR",JOptionPane.WARNING_MESSAGE);
                    }else{
                        int tPedido=JOptionPane.showConfirmDialog(null, "Es un pedido urgente?");
                        if(tPedido==0){
                            vecPed[indPed]=new PedidoUrgente(Fecha(),Fecha(),t);
                            indPed++;
                        }else{
                            vecPed[indPed]=new Pedido(Fecha(),Fecha(),t);
                            indPed++;
                        }
                    }
                    break;
            default:vecCV[indCon]=new CV(Fecha());
                    indCon++;
        }
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        String tp=JOptionPane.showInputDialog(null,"1. FACTURAS\n2. PEDIDOS\n3. CONTRATOS\n INGRESAR TIPO DE DOCUMENTO:").toUpperCase();
        switch(tp){
            case "FACTURAS": MostrarFactura();break;
            case "PEDIDOS": MostrarPedido();break;
            case "CONTRATOS": MostrarCV();break;
            default: JOptionPane.showMessageDialog(null,"LA RESPUSTA NO CONCUERDA CON LAS OPCIONES","ERROR",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnCambiarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPedidoActionPerformed
        int ID=Integer.parseInt(JOptionPane.showInputDialog(null,"INGRESE ID DEL PEDIDO"));
        if(CambiarPedido(ID)){
            JOptionPane.showMessageDialog(null,"EL PEDIDO FUE CAMBIADO EXITOSAMENTE","LISTO",JOptionPane.INFORMATION_MESSAGE);
            MostrarPedido();
        }else{
            JOptionPane.showMessageDialog(null,"NOSE SE ENCONTRO PEDIDO","ERROR",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCambiarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambiarPedido;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cboDoc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    // End of variables declaration//GEN-END:variables
}
