/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI1;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Frm_2 extends javax.swing.JFrame {
boolean x,y;
int vec1[]=new int [10],indice1;
int vec2[]=new int [10],indice2;
int vec3[]=new int [10],indice3;
    /**
     * Creates new form Frm_1
     */
    public Frm_2() {
        initComponents();
    }
    public void PoblarA(){
        int num;
        indice1=0;
         for(int i=0;i<vec1.length+1;i++){
            if(indice1<vec1.length){
               do{
               num=(int)(Math.random()*(300-1+1)+1);
                }while(num%5!=0);
                vec1[indice1]=num;
                indice1++;
            }
        }
    }
    public void PoblarB(){
        indice2=0;
        for(int c=0;c<vec2.length;c++){
            do{
                vec2[c]=(int)(Math.random()*(900-100+1)+100);
            }while(vec2[c]%7!=0);
            if(c>0){
                for(int x=0;x<indice2;x++){
                    while(vec2[x]==vec2[c]){
                        do{
                            vec2[c]=(int)(Math.random()*(900-100+1)+100);
                        }while(vec2[c]%7!=0);
                    }
                } 
            }
           indice2++;
        }
    }
    public void PoblarC(){
        indice3=0; 
            for(int i=0;i<20;i++){
                if(indice3<vec3.length){
                    if(i==0){
                        vec3[indice3]=vec1[i]*vec2[vec2.length-1];
                    }else{
                        vec3[indice3]=vec1[i]*vec2[vec2.length-(i+1)];
                    }
                    indice3++;
                } 
            }
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtA3 = new javax.swing.JTextArea();
        btnMostrarA = new javax.swing.JButton();
        btnMostrarB = new javax.swing.JButton();
        btnMostrarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtA1.setColumns(20);
        txtA1.setRows(5);
        jScrollPane1.setViewportView(txtA1);

        txtA2.setColumns(20);
        txtA2.setRows(5);
        jScrollPane2.setViewportView(txtA2);

        txtA3.setColumns(20);
        txtA3.setRows(5);
        jScrollPane3.setViewportView(txtA3);

        btnMostrarA.setText("MOSTRAR A");
        btnMostrarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAActionPerformed(evt);
            }
        });

        btnMostrarB.setText("MOSTRAR b");
        btnMostrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarBActionPerformed(evt);
            }
        });

        btnMostrarC.setText("MOSTRAR c");
        btnMostrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMostrarA)
                                .addGap(268, 268, 268)
                                .addComponent(jLabel1))
                            .addComponent(btnMostrarB)
                            .addComponent(btnMostrarC))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarA)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btnMostrarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAActionPerformed
        
        PoblarA();
        x=true;
        txtA1.setText(null);
        for(int c=0;c<indice1;c++){
            txtA1.append(vec1[c]+"\n");
        }
    }//GEN-LAST:event_btnMostrarAActionPerformed

    private void btnMostrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarBActionPerformed
        PoblarB();
        y=true;
        txtA2.setText(null);
        for(int c=0;c<indice2;c++){
            txtA2.append(vec2[c]+"\n");
        }
    }//GEN-LAST:event_btnMostrarBActionPerformed

    private void btnMostrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCActionPerformed
        if(x==true&&y==true){
            PoblarC();
            txtA3.setText(null);
            for(int c=0;c<indice3;c++){
                txtA3.append(vec3[c]+"\n");
            }
        }else{
            JOptionPane.showMessageDialog(this, "NO SE POBLO LOS VECTORES B O A","ALERTA",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnMostrarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarA;
    private javax.swing.JButton btnMostrarB;
    private javax.swing.JButton btnMostrarC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtA1;
    private javax.swing.JTextArea txtA2;
    private javax.swing.JTextArea txtA3;
    // End of variables declaration//GEN-END:variables
}
