/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio_4;

/**
 *
 * @author jmgut
 */
public class Laboratorio extends javax.swing.JFrame {
String vApellido[]=new String[15];
int vEdad[]=new int[15];
String vDni[]=new String[15];
char vTipoPrueba[]=new char[15];
char vResultado[]=new char[15];
int indice=0;
    /**
     * Creates new form Interfaz
     */
    public Laboratorio() {
        initComponents();
    }
    public boolean verificarClienteRegistrado(String n){
        for(int c=indice-1;c>=0;c--){
            if(vDni[c].equals(n))
                return true;
        }
        return false;
    } 
    public void Registrar(){
        String D=txtDNI.getText().trim();
        if(verificarClienteRegistrado(D)==false){
            vApellido[indice]=txtApellido.getText().trim();
            vEdad[indice]=Integer.parseInt(txtEdad.getText().trim());
            vDni[indice]=D;
            indice++;
        }else{
            UtilitarioCovid.setMensaje("Solo se realizar una prueba por persona");
        }
    }
    public int Buscar(String n){
        int pos=-1;
        for(int c=0;c<indice;c++){
            if(n.equals(vDni[c])){
                pos=c;
            }
        }
        return pos;
    }
    public void Mostrar(){
        txtA.setText("LISTA DE RESULTADOS\n");
        for(int i=0;i<indice;i++){
            txtA.append("PACIENTE "+(i+1)+"\n");
            txtA.append("   APELLIDO: "+vApellido[i]+"\n");
            txtA.append("   EDAD: "+vEdad[i]+"\n");
            txtA.append("   DNI: "+vDni[i]+"\n");
            if(vTipoPrueba[i]=='M'){
                txtA.append("   TIPO DE PRUEBA: MOLECULAR\n");
            }else if(vTipoPrueba[i]=='R'){
                txtA.append("   TIPO DE PRUEBA: RAPIDA\n");
            }else{
                txtA.append("   TIPO DE PRUEBA: NO REALIZADA\n");
            }
            if(vResultado[i]=='P'){
                txtA.append("   RESULTADO: POSITIVO\n");
            }else if(vResultado[i]=='N'){
                txtA.append("   RESULTADO: NEGATIVA\n");
            }else{
                txtA.append("   RESULTADO: NO REALIZADA\n");
            }
            txtA.append("\n");
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        btnRegistrarCliente = new javax.swing.JButton();
        btnRealizarExamen = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Apellido:");

        jLabel2.setText("Edad:");

        jLabel3.setText("DNI:");

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        btnRealizarExamen.setText("Realizar Examen");
        btnRealizarExamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarExamenActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRealizarExamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnRealizarExamen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        String t1=txtApellido.getText(),t2=txtEdad.getText(),t3=txtDNI.getText();
        if(indice<vApellido.length){
            if(t1.trim().length()>2&&t2.compareTo("")!=0&&t3.trim().compareTo("")!=0){
                Registrar();
            }else{
                UtilitarioCovid.setMensajeError("Los espacios de textos tiene que tener como minimo 2 caracteres.");
            }
        }else{
            UtilitarioCovid.setMensajeError("SOLO SE PERMITEN 15 PACIENTES");
        }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnRealizarExamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarExamenActionPerformed
        int p=Buscar(UtilitarioCovid.getMensaje("INSERTAR DNI DEL PACIENTE:"));
        if(p!=-1){
            int r=Integer.parseInt(UtilitarioCovid.getMensaje("Tipo de pruba:\n1 Prueba Molecular\n2 Prueba Rápida"));
            switch(r){
                case 1:vTipoPrueba[p]='M';
                        vResultado[p]=new PruebaMolecular().realizarPrueba();
                        break;
                case 2:vTipoPrueba[p]='R';
                        vResultado[p]=new PruebaRapida().realizarPrueba();
                        break;
                default:UtilitarioCovid.setMensajeError("LA RESPUESTA NO COINCIDE CON NINGUNA OPCION");
            }
            Mostrar();
        }else{
            UtilitarioCovid.setMensajeError("DEBE REGISTRARSE PRIMERO");
        }
    }//GEN-LAST:event_btnRealizarExamenActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        Mostrar();
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laboratorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRealizarExamen;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtEdad;
    // End of variables declaration//GEN-END:variables
}
