/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen;

import javax.swing.*;
/**
 *
 * @author JM Gutierrez
 */
public class Formulario extends JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }
    public void mostrarCar(Car e){
        txtA.append("OBJETO CAR\n");
        txtA.append("   MATRICULA: "+e.getMatricula()+"\n");
        txtA.append("   MARCA: "+e.getMarca()+"\n");
        txtA.append("   MODELO: "+e.getModelo()+"\n");
        txtA.append("   CAPACIDAD DE TANQUE: "+e.getCap_tanque()+"\n");
        txtA.append("   VELOCIDAD: "+e.getVelocidad()+"\n");
    }
    
    public void mostrarTruck(Truck e){
        
        txtA.append("OBJETO TRUCK\n");
        txtA.append("   MATRICULA: "+e.getMatricula()+"\n");
        txtA.append("   MARCA: "+e.getMarca()+"\n");
        txtA.append("   MODELO: "+e.getModelo()+"\n");
        txtA.append("   CAPACIDAD DE TANQUE: "+e.getCap_tanque()+"\n");
        txtA.append("   TIPO: "+e.getTipo()+"\n");
        txtA.append("   CARGA: "+e.getCarga()+"\n");
    }
    
    public void mostrarSuv(Suv e){
        
        txtA.append("OBJETO SUV\n");
        txtA.append("   MATRICULA: "+e.getMatricula()+"\n");
        txtA.append("   MARCA: "+e.getMarca()+"\n");
        txtA.append("   MODELO: "+e.getModelo()+"\n");
        txtA.append("   CAPACIDAD DE TANQUE: "+e.getCap_tanque()+"\n");
        txtA.append("   VELOCIDAD: "+e.getVelocidad()+"\n");
        txtA.append("   TRACCION: "+e.getTraccion()+"\n");
    }
    
    public void modificarCar(Car c){
        int e=Integer.parseInt(JOptionPane.showInputDialog("QUE DESEA MODIFICAR\n1.CAPACIDAD DE TANQUE\n2.VELOCIDAD"));
        if(e==1){
            int capacidad=Integer.parseInt(JOptionPane.showInputDialog("INGRESE CAPACIDAD DEL TANQUE:"));
            c.setCap_tanque(capacidad);
            JOptionPane.showMessageDialog(null,"SE MODIFICO LA CAPACIDAD DEL TANQUE");
            mostrarCar(c);
        }else if(e==2){
            int velocidad=Integer.parseInt(JOptionPane.showInputDialog("INGRESE VELOCIDAD:"));
            c.setVelocidad(velocidad);
            JOptionPane.showMessageDialog(null,"SE MODIFICO LA VELOCIDAD");
            mostrarCar(c);
        }else{
            JOptionPane.showMessageDialog(null,"ERROR DE INGRESO");
        }
    }
    
    public void modificarTruck(Truck t){
        int e=Integer.parseInt(JOptionPane.showInputDialog("QUE DESEA MODIFICAR\n1.TIPO\n2.CARGA"));
        if(e==1){
            String tipo=JOptionPane.showInputDialog("INGRESE TIPO:");
            t.setTipo(tipo);
            JOptionPane.showMessageDialog(null,"SE MODIFICO EL TIPO");
            mostrarTruck(t);
        }else if(e==2){
            double carga=Double.parseDouble(JOptionPane.showInputDialog("INGRESE CARGA:"));
            t.setCarga(carga);
            JOptionPane.showMessageDialog(null,"SE MODIFICO LA CARGA");
            mostrarTruck(t);
        }else{
            JOptionPane.showMessageDialog(null,"ERROR DE INGRESO");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        btnTruck = new javax.swing.JButton();
        btnSuv = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LA COCHERA");

        btnCar.setText("CAR");
        btnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarActionPerformed(evt);
            }
        });

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane1.setViewportView(txtA);

        btnTruck.setText("TRUCK");
        btnTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruckActionPerformed(evt);
            }
        });

        btnSuv.setText("SUV");
        btnSuv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addComponent(btnCar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSuv)
                        .addComponent(btnTruck, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCar, btnSuv, btnTruck});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTruck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuv)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarActionPerformed
        txtA.setText(null);
        Car c=new Car();
        JOptionPane.showMessageDialog(null,c.mensaje());
        mostrarCar(c);
        modificarCar(c);
    }//GEN-LAST:event_btnCarActionPerformed

    private void btnTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruckActionPerformed
        txtA.setText(null);
        Truck t=new Truck();
        JOptionPane.showMessageDialog(null,t.mensaje());
        mostrarTruck(t);
        modificarTruck(t);
    }//GEN-LAST:event_btnTruckActionPerformed

    private void btnSuvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuvActionPerformed
        txtA.setText(null);
        String marca=JOptionPane.showInputDialog("INGRESE MARCA:").toUpperCase();
        String modelo=JOptionPane.showInputDialog("INGRESE MODELO:").toUpperCase();
        Suv s=new Suv(marca, modelo);
        JOptionPane.showMessageDialog(null,s.mensaje());
        mostrarSuv(s);
    }//GEN-LAST:event_btnSuvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCar;
    private javax.swing.JButton btnSuv;
    private javax.swing.JButton btnTruck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA;
    // End of variables declaration//GEN-END:variables
}
